# Fly.io configuration for Yahuti Trade Engine API
app = "yahuti-trade-engine-api"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    restart_limit = 0
    timeout = "4s"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[processes]
  web = "node apps/api/dist/main.js"

# Auto-scaling configuration
[[vm.auto_start_machines]]
  min_machines_running = 1
  max_machines_running = 3

[[vm.auto_stop_machines]]
  enabled = true
  min_machines_running = 1